hundredrabbits/awesome-uxn

README.md
- New entries:
- Bunnymark,
- Sublime syntax
- Sections:
- Added the _Metadevelopment tools_ section with tools for writing assemblers and emulators (as opposed to writing Uxn code).
- Dropped the descriptions and project names in the _Uxntal language support_ section.
=> Add Bunnymark and Sublime syntax

README.md
=> Two small tweaks

README.md
It's my first time porting anything over to anything, and I learned a lot and had fun!
=> added Adafruit PyBadge

README.md
(if it's deemed awesome enough <3)
=> Add uxn-harp

README.md
This does a few things:
1. Fixes the uxntal-mode repo (renamed from tal-mode)
2. Adds a better link for regex.tal
3. Adds math32.tal
4. Adds femto and grep command-line tools
=> Update awesome-uxn projects

README.md
shameless plug. i hope it is considered awesome :)
=> add uxn900

README.md
I noticed this one wasn't on awesome-uxn, so now it is :)
(yesterday somebody asked on irc if there were test roms)
=> Added link to the test suite of uxn repo

README.md
These libraries are fairly well-tested.
=> Add fix16.tal and alloc.tal libraries

README.md
Link format had changed a bit.
=> Fix micro link

README.md
edit: whoops, forgot to leave a comment
lunas is an Uxntal assembler I made that's written in Lua, with better error reporting than uxnasm
=> added lunas

README.md
[Lite XL](https://lite-xl.com) is a text editor written mainly in Lua that I like to use because it's so small (around 4mb when extracted, barebones version) and it's easy to make extensions for it, also called "plugins"
in this case I made an Uxntal syntax highlighter for it :)
I didn't do it now, I have been "working on it" on and off for almost half a month, but I uploaded it to the Lite XL plugin repository and put it here just now lol
=> syntax highlighter for Lite XL

README.md
=> Fix sublime text syntax highlight link

README.md
=> Add "Pinkie Run"

README.md
I wrote a little announcement post [here](https://llllllll.co/t/uxn-virtual-computer/46103/420?u=lynn).
=> Add chibicc-uxn (C compiler)

README.md
This project was announced in [various](https://social.noyu.me/@hikari/statuses/01H46X10WKDGC55ZZ3S4R5KA6X) [places](https://llllllll.co/t/uxn-virtual-computer/46103/435?u=hikari_no_yume). There is now a second release with some improvements.
=> Add oneko-uxn

README.md
As it stands it's currently more of a demo than a proper tool, but that may or may not change in the future.
=> Add svitlyna image viewer

README.md
It is confusing wich is the canonical test suite, I hope this helps avoid confusions.
=> Update README.md with "official" opctest.tal

README.md
This changes the links from d6's personal website to d6's personal repo.
=> Update d6's (Plastic Idolatry) website links.

README.md
I tried to get all the roms on this list (as well as others) into a big collection of pre-assmbled roms, and I think that would be helpful here.
=> Add collection of all roms

README.md
https://files.soxfox.me/pebble.jpg
https://files.soxfox.me/bifurcan.jpg
=> Add uxn-pebble
